[project]
name = "model-deployment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "catboost>=1.2.7",
    "fastapi>=0.115.6",
    "feature-engine>=1.8.2",
    "uvicorn>=0.34.0",
]
